"""Phase 5 OFX/QFX parser lift — free Plaid alternative.

OFX (Open Financial Exchange) is an industry-standard text format for
downloading bank statement transactions. Most major US banks offer it
free via online banking — no Plaid subscription required. ``ofxparse``
is the canonical Python library for parsing it (returns a typed object
tree with `Account`, `Statement`, `Transaction`).

Two cookie-shaped functions:

- ``parse_ofx_file(upload_file)``: returns dict preview (file_type='ofx',
  record_count, preview, filename, suggested_account_type) — mirrors parse_csv_file.
- ``parse_ofx_transactions(upload_file)``: returns list of normalized
  transaction records (same shape as ``parse_csv_transactions``) —
  consumable by ``routes/imports.py::upload_statement``.

Why this lifts the BOTH signatures and not just the transactions one:

- Preview lets clients show the user the first 10 lines — useful UX.
- The transactions list lets the route invoke persistence logic.

Constraints / scope:

- Pure OFX/QFX, no PDF (PDF stays on ``parse_pdf_file``).
- OCR'd OFX (image-only) is out of scope — Phase 5b.2 OCR module
  handles PDF OCR; OFX is always a text-format file at the bank.
- Currency + balance lookup are typed but not persisted (added
  Phase 8 if a user wants a ``Transaction.currency`` column).

Phase 52 — account type extraction. OFX files include the account
  type in the ``<ACCTTYPE>`` tag (CHECKING, SAVINGS, CREDITCARD,
  MONEYMRKT, etc.). We map these to canonical account types so the
  FE can prompt the user to confirm or auto-create the right type.

Tests:

- ``tests/test_ofx_parser.py`` constructs an OFX1 file in-memory by
  writing the standard ``OFXHEADER:100`` + ``DATA:OFXSGML`` headers
  followed by valid SGML, then asserts both functions return the right
  shape. We use ``ofxparse.OfxParser.parse()`` directly against the
  generated bytes so we don't need a 3rd-party bank OFX fixture.
"""
from datetime import datetime
from typing import Any

from ofxparse import OfxParser

# Phase 52 — OFX account-type mapping. OFX ``<ACCTTYPE>`` values
# (case-insensitive) → canonical account type.
_OFX_ACCT_TYPE_MAP: dict[str, str] = {
    "checking": "checking",
    "savings": "savings",
    "creditcard": "credit_card",
    "credit line": "credit_card",
    "money market": "savings",
    "moneymrkt": "savings",
    "line of credit": "loan",
    "loan": "loan",
    "mortgage": "mortgage",
    "investment": "investment",
    "ira": "ira",
    "401k": "401k",
    "hsa": "hsa",
    "529": "529",
}


def parse_ofx_file(upload_file: Any) -> dict[str, Any]:
    """Read an OFX/QFX bank statement; return preview metadata.

    ``record_count`` = total transactions across all accounts in the
    file. ``preview`` is the first 10 transactions as a list of dicts
    so the UI can render them without re-parsing.
    """
    upload_file.file.seek(0)
    try:
        ofx = OfxParser.parse(upload_file.file)
    except Exception as exc:
        raise ValueError(f"Could not parse OFX file: {exc}")

    all_transactions = []
    for account in ofx.accounts:
        statement = account.statement
        transactions = getattr(statement, "transactions", []) or []
        all_transactions.extend(transactions)

    preview_records = []
    for txn in all_transactions[:10]:
        preview_records.append(
            {
                "date": str(txn.date),
                "amount": float(txn.amount),
                "description": str(getattr(txn, "memo", "") or getattr(txn, "payee", "") or ""),
            }
        )

    return {
        "file_type": "ofx",
        "record_count": int(len(all_transactions)),
        "preview": preview_records,
        "filename": upload_file.filename,
        # Phase 52 — extract account type from the OFX file's first account.
        "suggested_account_type": _extract_ofx_account_type(ofx),
    }


def parse_ofx_transactions(upload_file: Any) -> list[dict[str, Any]]:
    """Parse an OFX/QFX bank statement into normalized transaction
    records. Returns ``[]`` (not an error) for OFX files with NO
    transactions (e.g. zero-balance reports). Otherwise returns a list
    of dicts with keys: ``transaction_date``, ``amount``,
    ``description``, ``merchant_name`` (None for OFX), ``is_pending``
    (False).
    """
    upload_file.file.seek(0)
    try:
        ofx = OfxParser.parse(upload_file.file)
    except Exception as exc:
        raise ValueError(f"Could not parse OFX file for transactions: {exc}")

    records: list[dict[str, Any]] = []
    for account in ofx.accounts:
        statement = account.statement
        transactions = getattr(statement, "transactions", []) or []
        for txn in transactions:
            description = (
                str(getattr(txn, "memo", "") or getattr(txn, "payee", "") or "").strip()
                or "Imported OFX transaction"
            )
            txn_date = txn.date
            # ofxparse returns a datetime; normalise it.
            if isinstance(txn_date, datetime):
                transaction_date = txn_date
            else:
                # ofxparse sometimes returns a date-only object; convert.
                transaction_date = datetime.combine(txn_date, datetime.min.time())

            records.append(
                {
                    "transaction_date": transaction_date,
                    "amount": float(txn.amount),
                    "description": description,
                    "merchant_name": None,
                    "is_pending": False,
                }
            )

    return records


def _extract_ofx_account_type(ofx: Any) -> str | None:
    """Phase 52 — map the OFX file's ``<ACCTTYPE>`` to a canonical
    account type. Returns ``None`` when the tag is missing or
    unrecognised (the route layer falls back to 'checking')."""
    try:
        for account in ofx.accounts:
            raw = getattr(account, "account_type", "") or ""
            if not raw:
                continue
            mapped = _OFX_ACCT_TYPE_MAP.get(raw.lower().strip())
            if mapped:
                return mapped
    except Exception:
        pass
    return None
