'use client'

import { GitCompareArrows, ShieldAlert } from 'lucide-react'
import { Button } from '@/components/ui'
import { formatDecimalString } from '@/lib/format'
import type { ScenarioComparison, ScenarioListItem, ScenarioComparisonSet } from '@/lib/api_scenarios'

interface ScenarioComparisonWorkspaceProps {
  items: ScenarioListItem[]
  selectedIds: string[]
  comparison: ScenarioComparisonSet | null
  error?: string | null
  onToggle: (id: string) => void
  onCompare: () => void
  loading?: boolean
}

function ComparisonTable({ comparisons }: { comparisons: Array<{ scenario_id: string; version_number: number; comparison: ScenarioComparison }> }) {
  return <div className="overflow-x-auto rounded-lg border border-outline-variant"><table className="min-w-[48rem] w-full text-left text-sm"><caption className="sr-only">Selected Scenario Lab comparison results</caption><thead className="bg-surface-container text-xs uppercase tracking-wide text-tertiary"><tr><th className="px-3 py-3 font-semibold">Scenario</th><th className="px-3 py-3 font-semibold">Ending net worth</th><th className="px-3 py-3 font-semibold">Difference</th><th className="px-3 py-3 font-semibold">Target</th><th className="px-3 py-3 font-semibold">Liquidity consumed</th></tr></thead><tbody className="divide-y divide-outline-variant">{comparisons.map((item) => <tr key={item.scenario_id}><th scope="row" className="px-3 py-3 font-mono text-xs font-semibold text-primary">{item.scenario_id.slice(0, 8)} · v{item.version_number}</th><td className="px-3 py-3 font-mono text-primary">{formatDecimalString(item.comparison.ending_net_worth)}</td><td className={`px-3 py-3 font-mono font-semibold ${item.comparison.difference_from_baseline.startsWith('-') ? 'text-danger-600' : 'text-success-600'}`}>{formatDecimalString(item.comparison.difference_from_baseline)}</td><td className="px-3 py-3 text-secondary">{item.comparison.target_reached === null ? 'Not provided' : item.comparison.target_reached ? 'Reached' : `Gap ${item.comparison.target_gap ? formatDecimalString(item.comparison.target_gap) : 'unavailable'}`}</td><td className="px-3 py-3 font-mono text-primary">{formatDecimalString(item.comparison.one_time_liquidity_consumed)}</td></tr>)}</tbody></table></div>
}

export default function ScenarioComparisonWorkspace({ items, selectedIds, comparison, error, onToggle, onCompare, loading = false }: ScenarioComparisonWorkspaceProps) {
  const active = items.filter((item) => item.lifecycle_state === 'active')
  return <section className="card p-5" aria-labelledby="scenario-comparison-heading"><div className="flex items-start gap-3"><GitCompareArrows className="mt-1 h-5 w-5 shrink-0 text-primary-600" aria-hidden="true" /><div><h2 id="scenario-comparison-heading" className="headline-sm text-primary">Compare saved scenarios</h2><p className="mt-1 text-sm leading-6 text-secondary">Choose one to three active scenarios explicitly. Atlas will reject incompatible baseline, currency, or model versions on the server.</p></div></div>{active.length === 0 ? <p className="mt-5 rounded-lg border border-dashed border-outline-variant p-4 text-sm text-secondary">Generate an active scenario before comparing.</p> : <fieldset className="mt-5 space-y-2"><legend className="text-xs font-semibold uppercase tracking-wide text-tertiary">Selected scenarios ({selectedIds.length}/3)</legend>{active.map((item) => <label key={item.scenario_id} className="flex cursor-pointer items-center gap-3 rounded-lg border border-outline-variant p-3 hover:border-primary-300"><input type="checkbox" checked={selectedIds.includes(item.scenario_id)} disabled={!selectedIds.includes(item.scenario_id) && selectedIds.length >= 3} onChange={() => onToggle(item.scenario_id)} className="h-4 w-4 accent-[var(--primary-500)]" /><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-primary">{item.scenario_id.slice(0, 8)} · version {item.version_number}</span><span className="block text-xs text-secondary">Ending net worth {formatDecimalString(item.ending_net_worth)} · {item.lifecycle_state}</span></span></label>)}</fieldset>}<div className="mt-5 flex flex-wrap items-center gap-3"><Button type="button" variant="primary" onClick={onCompare} disabled={loading || selectedIds.length < 1}>{loading ? 'Comparing on server…' : 'Compare selected scenarios'}</Button><span className="text-xs text-tertiary">The first three records are never selected automatically.</span></div>{error && <div className="mt-4 flex items-start gap-2 rounded-lg border border-warning-200 bg-warning-50 p-4 text-sm text-warning-800" role="alert"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" /><span>{error}</span></div>}{comparison && <div className="mt-6"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h3 className="headline-xs text-primary">Server comparison</h3><span className="text-xs text-tertiary">Baseline {comparison.baseline_forecast_id.slice(0, 12)} · v{comparison.baseline_version_number}</span></div><ComparisonTable comparisons={comparison.scenarios} /><p className="mt-3 text-xs leading-5 text-tertiary">All rows reference the same server-selected baseline. Band assumptions and freshness are available when each scenario is opened.</p></div>}</section>
}
