'use client'

import { CheckCircle2, CircleAlert, Clock3, ShieldCheck } from 'lucide-react'
import { formatDecimalString } from '@/lib/format'
import type { ScenarioBand, ScenarioComparison, ScenarioDecimal, ScenarioEnvelope } from '@/lib/api_scenarios'

const bands: readonly ScenarioBand[] = ['conservative', 'base', 'optimistic']

function money(value: ScenarioDecimal | null): string {
  return value === null ? 'Not provided' : formatDecimalString(value)
}

function signedMoney(value: ScenarioDecimal): string {
  return value.startsWith('-') ? `−${money(value.slice(1) as ScenarioDecimal)}` : `+${money(value)}`
}

function ComparisonGrid({ comparison }: { comparison: ScenarioComparison }) {
  return <div className="overflow-x-auto rounded-lg border border-outline-variant"><table className="min-w-[42rem] w-full text-left text-sm"><caption className="sr-only">Deterministic scenario band comparison against baseline</caption><thead className="bg-surface-container text-xs uppercase tracking-wide text-tertiary"><tr><th className="px-3 py-3 font-semibold">Band</th><th className="px-3 py-3 font-semibold">Baseline ending net worth</th><th className="px-3 py-3 font-semibold">Scenario ending net worth</th><th className="px-3 py-3 font-semibold">Difference</th><th className="px-3 py-3 font-semibold">Target</th></tr></thead><tbody className="divide-y divide-outline-variant">{bands.map((band) => { const item = comparison.deterministic_bands[band]; return <tr key={band}><th scope="row" className="px-3 py-3 font-semibold capitalize text-primary">{band}</th><td className="px-3 py-3 font-mono text-primary">{money(item.baseline_ending_net_worth)}</td><td className="px-3 py-3 font-mono text-primary">{money(item.scenario_ending_net_worth)}</td><td className={`px-3 py-3 font-mono font-semibold ${item.difference_from_baseline.startsWith('-') ? 'text-danger-600' : 'text-success-600'}`}>{signedMoney(item.difference_from_baseline)}</td><td className="px-3 py-3 text-secondary">{item.scenario_target_reached === null ? 'Not modeled' : item.scenario_target_reached ? 'Reached' : `Gap ${money(item.scenario_target_gap)}`}</td></tr>})}</tbody></table></div>
}

function DetailList({ title, items }: { title: string; items: string[] }) {
  return <div><h4 className="text-xs font-semibold uppercase tracking-wide text-tertiary">{title}</h4><ul className="mt-2 space-y-1 text-sm leading-6 text-secondary">{items.map((item) => <li key={item}>• {item}</li>)}</ul></div>
}

export default function ScenarioResult({ result }: { result: ScenarioEnvelope }) {
  const comparison = result.comparison
  const reached = comparison.target_reached
  return <section className="card p-5" aria-labelledby="scenario-result-heading" aria-live="polite">
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 h-5 w-5 shrink-0 text-primary-600" aria-hidden="true" /><div><p className="label-md text-secondary">Authoritative result</p><h2 id="scenario-result-heading" className="mt-1 headline-sm text-primary">What this change means against the baseline</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-secondary">Returned by Rules Service for version {result.version_number}. Atlas does not infer execution or success from a saved scenario.</p></div></div><span className="rounded-full border border-outline-variant px-3 py-1 text-xs font-semibold text-secondary">{result.lifecycle_state}</span></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-lg bg-surface-container p-4"><p className="text-xs text-tertiary">Ending net worth</p><p className="mt-2 font-mono text-lg font-semibold text-primary">{money(comparison.ending_net_worth)}</p><p className="mt-1 text-xs text-tertiary">{comparison.currency}</p></div><div className="rounded-lg bg-surface-container p-4"><p className="text-xs text-tertiary">Difference from baseline</p><p className={`mt-2 font-mono text-lg font-semibold ${comparison.difference_from_baseline.startsWith('-') ? 'text-danger-600' : 'text-success-600'}`}>{signedMoney(comparison.difference_from_baseline)}</p></div><div className="rounded-lg bg-surface-container p-4"><p className="text-xs text-tertiary">Target</p><p className="mt-2 font-mono text-lg font-semibold text-primary">{money(comparison.target_amount)}</p><p className="mt-1 text-xs text-secondary">{reached === null ? 'Not provided' : reached ? 'Reached in server result' : `Gap ${money(comparison.target_gap)}`}</p></div><div className="rounded-lg bg-surface-container p-4"><p className="text-xs text-tertiary">Contribution difference</p><p className="mt-2 font-mono text-lg font-semibold text-primary">{signedMoney(comparison.contribution_difference)}</p><p className="mt-1 text-xs text-secondary">Liquidity consumed: {money(comparison.one_time_liquidity_consumed)}</p></div></div>
    <div className="mt-6"><div className="mb-3 flex items-center justify-between gap-3"><div><h3 className="headline-xs text-primary">Deterministic range comparison</h3><p className="mt-1 text-xs text-secondary">Each band is a server-returned assumption set, not a probability range.</p></div><span className="flex items-center gap-1 text-xs text-tertiary"><Clock3 className="h-4 w-4" aria-hidden="true" />Monthly boundaries</span></div><ComparisonGrid comparison={comparison} /></div>
    <div className="mt-6 grid gap-5 md:grid-cols-2"><div className="rounded-lg border border-outline-variant p-4"><h3 className="headline-xs text-primary">Timing and freshness</h3><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between gap-4"><dt className="text-secondary">Data as of</dt><dd className="text-right text-primary">{comparison.source_freshness.data_as_of}</dd></div><div className="flex justify-between gap-4"><dt className="text-secondary">Age / maximum</dt><dd className="text-right text-primary">{comparison.source_freshness.data_age_days} / {comparison.source_freshness.max_data_age_days} days</dd></div><div className="flex justify-between gap-4"><dt className="text-secondary">Contribution window</dt><dd className="text-right text-primary">{comparison.timing_impact.contribution_start_date ?? 'Baseline'} → {comparison.timing_impact.contribution_stop_date ?? 'Horizon'}</dd></div><div className="flex justify-between gap-4"><dt className="text-secondary">Outflow boundary</dt><dd className="text-right text-primary">{comparison.timing_impact.one_time_outflow_date ?? 'None'}</dd></div></dl></div><div className="rounded-lg border border-outline-variant p-4"><h3 className="headline-xs text-primary">Server assumptions</h3><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between gap-4"><dt className="text-secondary">Period</dt><dd className="text-primary">{comparison.assumptions.period}</dd></div><div className="flex justify-between gap-4"><dt className="text-secondary">Contribution timing</dt><dd className="text-primary">{comparison.assumptions.contribution_timing}</dd></div><div className="flex justify-between gap-4"><dt className="text-secondary">Inflation rate</dt><dd className="font-mono text-primary">{comparison.assumptions.annual_inflation_rate}</dd></div><div className="flex justify-between gap-4"><dt className="text-secondary">Probability claims</dt><dd className="font-semibold text-primary">None</dd></div></dl></div></div>
    <details className="mt-5 rounded-lg border border-outline-variant p-4"><summary className="cursor-pointer text-sm font-semibold text-primary focus-visible:outline-2 focus-visible:outline-primary">Technical provenance and limitations</summary><div className="mt-4 grid gap-5 md:grid-cols-2"><div className="space-y-4"><DetailList title="Warnings" items={comparison.warnings} /><DetailList title="Limitations" items={comparison.limitations} /></div><div className="space-y-2 text-xs leading-5 text-tertiary"><p>Baseline forecast {result.baseline_forecast_id}, version {result.baseline_version_number}.</p><p>Model {result.model_version}; calculation {result.calculation_version}.</p><p>Scenario identity {result.scenario_id}; immutable version {result.version_id}.</p></div></div></details>
    <p className="mt-5 flex items-start gap-2 text-xs leading-5 text-tertiary"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary-600" aria-hidden="true" />A recorded scenario is analysis history only. It does not execute a contribution, move money, or guarantee an outcome.</p>
  </section>
}
