// Headroom.js Initialization Utility
// Generated by headroom-setup skill
// Copy and customize this file for your project's needs

import Headroom from 'headroom.js';

/**
 * Initialize Headroom.js on a given element
 * @param {string|Element} selector - CSS selector string or DOM element
 * @param {Partial<any>} options - Headroom.js configuration options
 * @returns {Headroom | null} - The Headroom instance or null if element not found
 */
export function initHeadroom(selector: string | Element, options: Partial<any> = {}): Headroom | null {
  // Get the element
  const element: Element | null = typeof selector === 'string'
    ? document.querySelector(selector)
    : selector as Element;

  if (!element) {
    console.warn('Headroom.js: Element not found for selector:', selector);
    return null;
  }

  // Default configuration
  const defaultOptions = {
    offset: 0,
    tolerance: {
      up: 0,
      down: 0
    },
    classes: {
      initial: 'headroom',
      pinned: 'headroom--pinned',
      unpinned: 'headroom--unpinned',
      top: 'headroom--top',
      notTop: 'headroom--not-top',
      bottom: 'headroom--bottom',
      notBottom: 'headroom--not-bottom'
    }
  };

  // Merge options
  const config = { ...defaultOptions, ...options };

  // Create and initialize Headroom instance
  const headroom = new Headroom(element, config);
  headroom.init();

  // Idempotent destroy with typeof guard: headroom.js strips internal
  // refs after the first destroy(); React 18 StrictMode double-mount
  // fires cleanup twice (the second invocation throws "Cannot read
  // properties of undefined (reading 'destroy')"). Some headroom.js
  // builds also expose `destroy` only after `init()` returns, so the
  // typeof guard covers both the re-entrant case and the build that
  // doesn't ship a `destroy` method at all (we degrade to a no-op).
  if (typeof headroom.destroy === 'function') {
    let destroyed = false;
    const originalDestroy = headroom.destroy.bind(headroom);
    headroom.destroy = () => {
      if (destroyed) return;
      destroyed = true;
      if ((headroom as any).scrollTracker) {
        originalDestroy();
      }
    };
  }

  return headroom;
}

// Export a default initializer for common use cases
export function initDefaultHeader(): Headroom | null {
  return initHeadroom('header, .header, [data-header]', {
    offset: 100,
    tolerance: {
      up: 10,
      down: 0
    },
    classes: {
      pinned: 'slide-down',
      unpinned: 'slide-up'
    }
  });
}

export default { initHeadroom, initDefaultHeader };
